package com.esom.bank.common.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.tencent.mmkv.MMKV
import java.nio.charset.StandardCharsets
import java.security.KeyStore
import javax.crypto.KeyGenerator
import javax.crypto.Mac
import javax.crypto.SecretKey

/**
 * Provides one device-bound MMKV encryption key. The key material is generated by
 * Android Keystore and is never persisted in app-readable storage.
 */
object SecureMmkv {
    private const val KEYSTORE = "AndroidKeyStore"
    private const val KEY_ALIAS = "com.esom.bank.mmkv.key"
    private const val MIGRATION_STORE = "SecureMmkvMigration"
    private const val MIGRATION_PREFIX = "encrypted_"
    private const val SEED = "com.esom.bank.mmkv.v1"

    private val lock = Any()
    private val migrationStorage by lazy {
        MMKV.mmkvWithID(MIGRATION_STORE, MMKV.SINGLE_PROCESS_MODE)
    }

    fun storage(id: String): MMKV = synchronized(lock) {
        val cryptKey = cryptKey()
        val marker = MIGRATION_PREFIX + id
        if (!migrationStorage.decodeBool(marker, false)) {
            // Existing versions used plaintext MMKV. Rekey it in place so an upgrade
            // does not silently discard the user's credentials and settings.
            val legacyStorage = MMKV.mmkvWithID(id, MMKV.MULTI_PROCESS_MODE)
            check(legacyStorage.reKey(cryptKey)) {
                "Unable to encrypt MMKV storage: $id"
            }
            migrationStorage.encode(marker, true)
        }
        MMKV.mmkvWithID(id, MMKV.MULTI_PROCESS_MODE, cryptKey)
    }

    private fun cryptKey(): String {
        val keyStore = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        val secretKey = (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)
            ?: generateKey()
        val mac = Mac.getInstance("HmacSHA256").apply {
            init(secretKey)
        }
        // MMKV accepts at most 16 bytes for the encryption key. Hex encoding
        // the first eight HMAC bytes gives exactly 16 ASCII bytes.
        return mac.doFinal(SEED.toByteArray(StandardCharsets.UTF_8))
            .take(8)
            .joinToString("") { byte -> "%02x".format(byte.toInt() and 0xff) }
    }

    private fun generateKey(): SecretKey {
        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_HMAC_SHA256,
            KEYSTORE
        )
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY
            )
                .setDigests(KeyProperties.DIGEST_SHA256)
                .build()
        )
        return generator.generateKey()
    }
}
